name: Check if download links are working

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Run imgsync in download mode only
      run: glance-imgsync --download-only sync
